version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finansik
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    command: sh -c "npm run prisma:deploy && npm run build && npm start"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/finansik?schema=public
      JWT_SECRET: dev_secret_change_me
      PORT: 3000
    depends_on:
      - db
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
  gateway:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - adminer
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "gateway:80"
    environment:
      - NGROK_AUTHTOKEN=33n6dGDcYAehXDyYUpfnyTk2xK3_7eMkewDWdM1B4WRSjq6xk
    depends_on:
      - gateway
volumes:
  db_data:



